// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWP_BE.Data;

#nullable disable

namespace SWP_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310140406_InitialSupabase")]
    partial class InitialSupabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWP_BE.Models.ReputationRule", b =>
            {
                b.Property<int>("RuleID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleID"));

                b.Property<string>("Category")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("RuleName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Value")
                    .HasColumnType("integer");

                b.HasKey("RuleID");

                b.ToTable("ReputationRules");

                b.HasData(
                    new { RuleID = 1, Category = "Reward", Description = "Hoàn thành ngay lần đầu (0 reject)", IsActive = true, RuleName = "Reward_Perfect", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8081), Value = 20 },
                    new { RuleID = 2, Category = "Bonus", Description = "Thưởng thêm nếu RateComplete > 95%", IsActive = true, RuleName = "Bonus_HighRate", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8091), Value = 2 },
                    new { RuleID = 3, Category = "Penalty", Description = "Trừ điểm khi Approve ở lần sửa 2", IsActive = true, RuleName = "Penalty_Reject_2", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8093), Value = -5 },
                    new { RuleID = 4, Category = "Penalty", Description = "Trừ điểm khi Approve ở lần sửa 3", IsActive = true, RuleName = "Penalty_Reject_3", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8094), Value = -10 },
                    new { RuleID = 5, Category = "Penalty", Description = "Task bị Fail (Reject lần 4)", IsActive = true, RuleName = "Penalty_Task_Fail", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8095), Value = -20 },
                    new { RuleID = 6, Category = "Threshold", Description = "Ngưỡng >= 50đ", IsActive = true, RuleName = "High_Threshold", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8096), Value = 50 },
                    new { RuleID = 7, Category = "Threshold", Description = "Ngưỡng 20 - 50đ", IsActive = true, RuleName = "Low_Threshold", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8097), Value = 20 },
                    new { RuleID = 8, Category = "Limit", Description = "Max 3 task", IsActive = true, RuleName = "Max_Task_High", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8098), Value = 3 },
                    new { RuleID = 9, Category = "Limit", Description = "Max 2 task", IsActive = true, RuleName = "Max_Task_Normal", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8099), Value = 2 },
                    new { RuleID = 10, Category = "Limit", Description = "Max 1 task", IsActive = true, RuleName = "Max_Task_Warning", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8100), Value = 1 },
                    new { RuleID = 11, Category = "Limit", Description = "Số task Fail liên tiếp để bị khóa tài khoản", IsActive = true, RuleName = "Max_Consecutive_Fails", UpdatedAt = new DateTime(2026, 3, 10, 21, 4, 5, 866, DateTimeKind.Local).AddTicks(8101), Value = 3 }
                );
            });

            modelBuilder.Entity("SWP_BE.Models.Task", b =>
            {
                b.Property<Guid>("TaskID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid?>("AnnotatorID")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("CompletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("CurrentRound")
                    .HasColumnType("integer");

                b.Property<DateTime>("Deadline")
                    .HasColumnType("timestamp with time zone");

                b.Property<double>("RateComplete")
                    .HasColumnType("double precision");

                b.Property<int>("RejectCount")
                    .HasColumnType("integer");

                b.Property<Guid?>("ReviewerID")
                    .HasColumnType("uuid");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<double>("SubmissionRate")
                    .HasColumnType("double precision");

                b.Property<string>("TaskName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ProjectID")
                    .HasColumnType("uuid");

                b.HasKey("TaskID");

                b.HasIndex("AnnotatorID");
                b.HasIndex("ProjectID");
                b.HasIndex("ReviewerID");

                b.ToTable("Tasks");
            });

#pragma warning restore 612, 618
        }
    }
}